In [1]:
import numpy as np

scores = np.random.randint(50, 101,size=(50, 5))
scores

array([[ 52,  96,  81,  95,  78],
       [ 86,  78,  83,  96,  93],
       [ 94,  82,  84,  97,  92],
       [ 58,  73,  77,  80,  85],
       [ 65,  84,  69,  71,  74],
       [ 70,  80,  55,  87,  65],
       [ 90,  96,  74,  92,  59],
       [ 54,  69,  80,  50,  62],
       [ 60,  93,  84,  56,  67],
       [ 85,  51,  68,  75,  72],
       [ 60,  69,  52,  74,  82],
       [100,  72,  58,  70,  82],
       [ 95,  94,  96,  92,  63],
       [ 81,  89,  68,  75,  84],
       [ 89,  94,  98,  61,  68],
       [ 50,  93,  50,  62,  81],
       [ 55,  58,  75,  73,  93],
       [ 52,  73,  52,  83,  68],
       [ 64,  81,  63,  73,  99],
       [ 66,  96,  65,  74,  59],
       [ 54,  50,  65,  95,  76],
       [ 68,  94,  75,  82,  87],
       [ 98,  60,  70,  96,  56],
       [ 52,  98,  63,  51,  63],
       [ 82,  55,  64,  79,  92],
       [ 85,  64,  55,  81,  97],
       [ 66,  80,  54,  59,  95],
       [ 67,  54,  58,  95,  53],
       [ 66,  73,  90,  58,  69],
       [ 71,  69,  57,  56,  62],
       [ 82,  51, 100,  60,  69],
       [ 79,  65,  72,  56,  87],
       [ 58,  68,  67,  66,  62],
       [ 83, 100,  60,  87,  97],
       [ 51,  72,  93,  84,  79],
       [ 94,  64,  98,  93,  59],
       [ 59,  51,  78,  87,  62],
       [ 55,  97,  61,  67, 100],
       [ 64,  98,  71,  63,  96],
       [ 54,  92,  53,  93,  60],
       [ 79,  83,  98,  96,  87],
       [ 61,  81,  64,  71,  54],
       [ 67,  71,  53,  92,  87],
       [ 81,  64,  56,  94,  73],
       [ 64,  56,  78,  61,  64],
       [ 72,  61,  55,  66,  88],
       [ 77,  70,  88,  81,  94],
       [ 57,  70,  74,  94,  80],
       [ 95,  68,  64,  61,  96],
       [ 85,  98,  78,  99,  59]], dtype=int32)

In [2]:
import pandas as pd

df = pd.DataFrame(scores,
            index = [f"學生{i+1}" for i in range(50)],
            columns = ["國文","英文","數學","地理","歷史"]
)
df

       國文   英文   數學  地理   歷史
學生1    52   96   81  95   78
學生2    86   78   83  96   93
學生3    94   82   84  97   92
學生4    58   73   77  80   85
學生5    65   84   69  71   74
學生6    70   80   55  87   65
學生7    90   96   74  92   59
學生8    54   69   80  50   62
學生9    60   93   84  56   67
學生10   85   51   68  75   72
學生11   60   69   52  74   82
學生12  100   72   58  70   82
學生13   95   94   96  92   63
學生14   81   89   68  75   84
學生15   89   94   98  61   68
學生16   50   93   50  62   81
學生17   55   58   75  73   93
學生18   52   73   52  83   68
學生19   64   81   63  73   99
學生20   66   96   65  74   59
學生21   54   50   65  95   76
學生22   68   94   75  82   87
學生23   98   60   70  96   56
學生24   52   98   63  51   63
學生25   82   55   64  79   92
學生26   85   64   55  81   97
學生27   66   80   54  59   95
學生28   67   54   58  95   53
學生29   66   73   90  58   69
學生30   71   69   57  56   62
學生31   82   51  100  60   69
學生32   79   65   72  56   87
學生33   58   68   67  66   62
學生34   83  100   60  87   97
學生35   51   72   93  84   79
學生36   94   64   98  93   59
學生37   59   51   78  87   62
學生38   55   97   61  67  100
學生39   64   98   71  63   96
學生40   54   92   53  93   60
學生41   79   83   98  96   87
學生42   61   81   64  71   54
學生43   67   71   53  92   87
學生44   81   64   56  94   73
學生45   64   56   78  61   64
學生46   72   61   55  66   88
學生47   77   70   88  81   94
學生48   57   70   74  94   80
學生49   95   68   64  61   96
學生50   85   98   78  99   59